
stages:
  - build
  - test

build :
  stage: build
  script:
    - cd ..
    - cp -R /root/* .
    - ./install_lima_submodule
    - cd lima/camera/pilatus
    - cp -R ../../../lima-camera-pilatus/* .
    - cd ../..
    - ./install.sh camera/pilatus python tests cbf fits tiff hdf5 config
    - cd ../lima-camera-pilatus
    - cp -R ../lima .
  artifacts:
    paths:
    - lima/
  only:
    - cmake
    
test :
  stage: test
  dependencies:
    - build
  script:
    - cd ..
    - cp -R lima-camera-pilatus/lima .
    - cd lima/build/
    - ctest --timeout 10
  only:
    - cmake
